---@diagnostic disable: undefined-global

QuickFits = QuickFits or {}
QuickFits.Localization = QuickFits.Localization or {}

local Localization = QuickFits.Localization

---@diagnostic disable-next-line: deprecated
local unpackArgs = (table and table.unpack) or unpack

Localization.KEY_PREFIX = "UI_QuickFits_"
Localization.PREVIEW_LANGUAGE_AUTO = "AUTO"

local PREVIEW_LANGUAGE_LABELS = {
    AUTO = "Auto (game language)",
    EN = "English",
    DE = "Deutsch",
    ES = "Espanol",
    FR = "Francais",
    PTBR = "Portugues (Brasil)",
    RU = "Russkiy",
    CN = "JianTi ZhongWen",
}

local STRINGS = {
    EN = {
        bind_open = "Open Quick Fits",
        title = "Quick Fits",
        inventory_button = "Quick Fits",
        context_open = "Quick Fits...",
        editor_editing_named = "Editing: %1",
        editor_editing_new = "Editing: New Outfit",
        fallback_outfit_name = "Outfit",
        debug_full_type = "fullType=%1",
        debug_body = "body=%1",
        debug_item_type = "itemType=%1",
        debug_included_false = "included=false",
        debug_ignored_true = "ignored=true",
        button_save = "Save",
        button_capture_current = "Set To Currently Worn",
        button_new = "New",
        button_wear = "Wear",
        button_add = "Add",
        button_take_off = "Take Off",
        button_place_container = "Place In Container",
        button_grab_all = "Grab All",
        button_delete = "Delete",
        button_stop = "Stop",
        tooltip_wear = "Matches your worn gear to this outfit exactly, unequipping anything not in it first.",
        tooltip_add = "Layers this outfit onto what you are already wearing, replacing only conflicting slots.",
        tooltip_take_off = "Removes only this outfit's worn items and puts them into your inventory.",
        tooltip_place_container =
        "Moves outfit items into a container, using the selected container first and then the nearest container.",
        tooltip_grab_all =
        "Finds outfit items in selected or nearby external containers and moves them into your inventory.",
        label_outfits = "Outfits",
        label_items_in_outfit = "Items in Outfit",
        label_item_singular = "item",
        label_item_plural = "items",
        label_worn = "WORN",
        drop_hint_drag_here = "Drag wearable items here",
        drop_hint_capture = "or use Capture Worn to pull from your current gear",
        drop_hint_release = "Release to add dragged wearable items",
        debug_preview_language = "Preview Language",
        progress_interrupted = "Interrupted",
        progress_action_removing = "Removing",
        progress_action_wearing = "Wearing",
        progress_action_moving = "Moving",
        progress_status_count = "%1 (%2 / %3)",
        progress_status_with_item = "%1: %2 (%3 / %4)",
        progress_completed_phase = "Completed: %1 (%2 / %3)",
        progress_interrupted_phase = "Interrupted: %1 (%2 / %3)",
        result_apply_failed = "Quick Fits could not apply the selected outfit.",
        result_action_apply = "applied.",
        result_action_remove = "taken off.",
        result_action_add = "added.",
        result_action_wear = "worn exactly.",
        result_action_place = "placed in container.",
        result_action_grab = "grabbed into inventory.",
        result_outfit_action = "%1 %2",
        result_equipped = "Equipped %1 item(s).",
        result_removed = "Removed %1 item(s).",
        result_blocked = "Blocked by worn items: %1.",
        result_moved = "Moved %1 item(s).",
        result_moved_target = "Moved %1 item(s) into %2.",
        result_missing = "Missing: %1.",
        draft_error_wearable_duplicates = "Only wearable items can be added, and dragged duplicates were ignored.",
        draft_overlay_wearable_duplicates = "Only wearable items belong here. Duplicates were ignored.",
        draft_error_only_wearable = "Only wearable items can be added to a Quick Fit.",
        draft_overlay_only_wearable = "Only wearable items can be dropped into an outfit.",
        draft_error_already_present = "Those items are already in this Quick Fit.",
        draft_overlay_already_present = "That wearable is already in this outfit.",
        draft_added = "Added %1 wearable item(s) to the draft.",
        draft_added_ignored = " Ignored %1 duplicate(s) and %2 non-wearable item(s).",
        status_selected_outfit = "Selected outfit: %1",
        status_captured_current = "Captured the player's current worn items into the editor.",
        status_new_draft = "Started a new empty outfit draft. Drag wearable items in or use Capture Worn.",
        status_saved_changes = "Saved changes to outfit: %1",
        status_saved_new = "Saved outfit: %1",
        status_select_before_delete = "Select an outfit before deleting it.",
        delete_confirm = "Delete %1?",
        status_deleted = "Deleted the selected outfit.",
        status_delete_failed = "Quick Fits could not delete the selected outfit.",
        status_select_before_wear = "Select an outfit before wearing it.",
        status_select_before_add = "Select an outfit before adding it.",
        status_select_before_place = "Select an outfit before placing it in a container.",
        status_select_before_grab = "Select an outfit before grabbing it from nearby containers.",
        status_select_before_remove = "Select an outfit before taking it off.",
        error_no_player = "No player was available.",
        error_select_outfit_first = "Select an outfit first.",
        error_no_container = "No selected or nearby container was available for Quick Fits.",
        error_no_external_container = "No selected or nearby external container was available for Quick Fits.",
        error_save_empty = "Select at least one worn item to save this outfit.",
        error_rename_missing = "Enter a name before renaming the outfit.",
        default_outfit_name = "Outfit %1",
        container_generic = "container",
        container_inventory = "inventory",
        container_nearby = "nearby container",
    },
    DE = {
        bind_open = "Quick Fits offnen",
        title = "Quick Fits",
        inventory_button = "Quick Fits",
        context_open = "Quick Fits...",
        editor_editing_named = "Bearbeiten: %1",
        editor_editing_new = "Bearbeiten: Neues Outfit",
        fallback_outfit_name = "Outfit",
        debug_full_type = "fullType=%1",
        debug_body = "Korper=%1",
        debug_item_type = "itemType=%1",
        debug_included_false = "included=false",
        debug_ignored_true = "ignored=true",
        button_save = "Speichern",
        button_capture_current = "Aktuell Getragenes Ubernehmen",
        button_new = "Neu",
        button_wear = "Anziehen",
        button_add = "Hinzufugen",
        button_take_off = "Ausziehen",
        button_place_container = "In Behalter Legen",
        button_delete = "Loschen",
        button_stop = "Stoppen",
        tooltip_wear =
        "Gleicht deine getragene Ausrustung exakt an dieses Outfit an und zieht zuerst alles aus, was nicht dazugehort.",
        tooltip_add = "Legt dieses Outfit uber das an, was du bereits tragt, und ersetzt nur konfliktierende Slots.",
        tooltip_take_off = "Entfernt nur die getragenen Teile dieses Outfits und legt sie in dein Inventar.",
        tooltip_place_container =
        "Verschiebt Outfit-Gegenstande in einen Behalter, zuerst den ausgewahlten und dann den nachstgelegenen.",
        label_outfits = "Outfits",
        label_items_in_outfit = "Gegenstande im Outfit",
        label_item_singular = "Gegenstand",
        label_item_plural = "Gegenstande",
        label_worn = "GETRAGEN",
        drop_hint_drag_here = "Ziehe tragbare Gegenstande hierher",
        drop_hint_capture = "oder nutze Getragenes Ubernehmen fur deine aktuelle Ausrustung",
        drop_hint_release = "Loslassen, um gezogene tragbare Gegenstande hinzuzufugen",
        debug_preview_language = "Vorschau-Sprache",
        progress_interrupted = "Unterbrochen",
        progress_completed_phase = "Abgeschlossen: %1 (%2 / %3)",
        result_apply_failed = "Quick Fits konnte das ausgewahlte Outfit nicht anwenden.",
        result_action_apply = "angewendet.",
        result_action_remove = "ausgezogen.",
        result_action_add = "hinzugefugt.",
        result_action_wear = "exakt angezogen.",
        result_action_place = "im Behalter abgelegt.",
        result_outfit_action = "%1 %2",
        result_equipped = "%1 Gegenstand(e) angezogen.",
        result_removed = "%1 Gegenstand(e) entfernt.",
        result_blocked = "Durch getragene Gegenstande blockiert: %1.",
        result_moved = "%1 Gegenstand(e) verschoben.",
        result_moved_target = "%1 Gegenstand(e) nach %2 verschoben.",
        result_missing = "Fehlt: %1.",
        draft_error_wearable_duplicates =
        "Nur tragbare Gegenstande konnen hinzugefugt werden, doppelte gezogene Eintrage wurden ignoriert.",
        draft_overlay_wearable_duplicates = "Hier gehoren nur tragbare Gegenstande hin. Duplikate wurden ignoriert.",
        draft_error_only_wearable = "Nur tragbare Gegenstande konnen zu einem Quick Fit hinzugefugt werden.",
        draft_overlay_only_wearable = "Nur tragbare Gegenstande konnen in ein Outfit gezogen werden.",
        draft_error_already_present = "Diese Gegenstande sind bereits in diesem Quick Fit.",
        draft_overlay_already_present = "Dieses tragbare Teil ist bereits in diesem Outfit.",
        draft_added = "%1 tragbare(r) Gegenstand(e) zum Entwurf hinzugefugt.",
        draft_added_ignored = " %1 Duplikat(e) und %2 nicht tragbare Gegenstand(e) ignoriert.",
        status_selected_outfit = "Ausgewahltes Outfit: %1",
        status_captured_current = "Die aktuell getragenen Gegenstande des Spielers wurden in den Editor ubernommen.",
        status_new_draft =
        "Neuer leerer Outfit-Entwurf gestartet. Ziehe tragbare Gegenstande hinein oder nutze Getragenes Ubernehmen.",
        status_saved_changes = "Anderungen am Outfit gespeichert: %1",
        status_saved_new = "Outfit gespeichert: %1",
        status_select_before_delete = "Wahle ein Outfit, bevor du es loschst.",
        delete_confirm = "%1 loschen?",
        status_deleted = "Das ausgewahlte Outfit wurde geloscht.",
        status_delete_failed = "Quick Fits konnte das ausgewahlte Outfit nicht loschen.",
        status_select_before_wear = "Wahle ein Outfit, bevor du es anziehst.",
        status_select_before_add = "Wahle ein Outfit, bevor du es hinzufugst.",
        status_select_before_place = "Wahle ein Outfit, bevor du es in einen Behalter legst.",
        status_select_before_remove = "Wahle ein Outfit, bevor du es ausziehst.",
        error_no_player = "Kein Spieler verfugbar.",
        error_select_outfit_first = "Wahle zuerst ein Outfit.",
        error_no_container = "Kein ausgewahlter oder naher Behalter fur Quick Fits verfugbar.",
        error_save_empty = "Wahle mindestens einen getragenen Gegenstand, um dieses Outfit zu speichern.",
        error_rename_missing = "Gib einen Namen ein, bevor du das Outfit umbenennst.",
        default_outfit_name = "Outfit %1",
        container_generic = "Behalter",
        container_nearby = "naher Behalter",
    },
    ES = {
        bind_open = "Abrir Quick Fits",
        title = "Quick Fits",
        inventory_button = "Quick Fits",
        context_open = "Quick Fits...",
        editor_editing_named = "Editando: %1",
        editor_editing_new = "Editando: Atuendo Nuevo",
        fallback_outfit_name = "Atuendo",
        debug_full_type = "fullType=%1",
        debug_body = "cuerpo=%1",
        debug_item_type = "itemType=%1",
        debug_included_false = "included=false",
        debug_ignored_true = "ignored=true",
        button_save = "Guardar",
        button_capture_current = "Usar Lo Que Llevo Puesto",
        button_new = "Nuevo",
        button_wear = "Ponerse",
        button_add = "Anadir",
        button_take_off = "Quitar",
        button_place_container = "Poner En Contenedor",
        button_delete = "Eliminar",
        button_stop = "Detener",
        tooltip_wear =
        "Hace coincidir exactamente tu equipo puesto con este atuendo, quitando primero cualquier cosa que no forme parte de el.",
        tooltip_add = "Coloca este atuendo sobre lo que ya llevas puesto, sustituyendo solo las ranuras en conflicto.",
        tooltip_take_off = "Quita solo los objetos puestos de este atuendo y los deja en tu inventario.",
        tooltip_place_container =
        "Mueve los objetos del atuendo a un contenedor, usando primero el contenedor seleccionado y luego el mas cercano.",
        label_outfits = "Atuendos",
        label_items_in_outfit = "Objetos del Atuendo",
        label_item_singular = "objeto",
        label_item_plural = "objetos",
        label_worn = "PUESTO",
        drop_hint_drag_here = "Arrastra aqui objetos que se puedan vestir",
        drop_hint_capture = "o usa Capturar Lo Vestido para tomar tu equipo actual",
        drop_hint_release = "Suelta para anadir los objetos arrastrados",
        debug_preview_language = "Idioma de Vista Previa",
        progress_interrupted = "Interrumpido",
        progress_completed_phase = "Completado: %1 (%2 / %3)",
        result_apply_failed = "Quick Fits no pudo aplicar el atuendo seleccionado.",
        result_action_apply = "aplicado.",
        result_action_remove = "quitado.",
        result_action_add = "anadido.",
        result_action_wear = "puesto exactamente.",
        result_action_place = "colocado en el contenedor.",
        result_outfit_action = "%1 %2",
        result_equipped = "Equipados %1 objeto(s).",
        result_removed = "Quitados %1 objeto(s).",
        result_blocked = "Bloqueado por objetos puestos: %1.",
        result_moved = "Movidos %1 objeto(s).",
        result_moved_target = "Movidos %1 objeto(s) a %2.",
        result_missing = "Faltan: %1.",
        draft_error_wearable_duplicates =
        "Solo se pueden anadir objetos que se puedan vestir y se ignoraron los duplicados arrastrados.",
        draft_overlay_wearable_duplicates = "Aqui solo van objetos que se puedan vestir. Se ignoraron los duplicados.",
        draft_error_only_wearable = "Solo se pueden anadir objetos que se puedan vestir a un Quick Fit.",
        draft_overlay_only_wearable = "Solo se pueden soltar objetos que se puedan vestir en un atuendo.",
        draft_error_already_present = "Esos objetos ya estan en este Quick Fit.",
        draft_overlay_already_present = "Ese objeto vestible ya esta en este atuendo.",
        draft_added = "Se anadieron %1 objeto(s) vestible(s) al borrador.",
        draft_added_ignored = " Se ignoraron %1 duplicado(s) y %2 objeto(s) no vestible(s).",
        status_selected_outfit = "Atuendo seleccionado: %1",
        status_captured_current = "Se capturaron en el editor los objetos que lleva puestos el jugador.",
        status_new_draft =
        "Se inicio un borrador vacio de atuendo. Arrastra objetos vestibles o usa Capturar Lo Vestido.",
        status_saved_changes = "Cambios guardados en el atuendo: %1",
        status_saved_new = "Atuendo guardado: %1",
        status_select_before_delete = "Selecciona un atuendo antes de eliminarlo.",
        delete_confirm = "Eliminar %1?",
        status_deleted = "Se elimino el atuendo seleccionado.",
        status_delete_failed = "Quick Fits no pudo eliminar el atuendo seleccionado.",
        status_select_before_wear = "Selecciona un atuendo antes de ponertelo.",
        status_select_before_add = "Selecciona un atuendo antes de anadirlo.",
        status_select_before_place = "Selecciona un atuendo antes de ponerlo en un contenedor.",
        status_select_before_remove = "Selecciona un atuendo antes de quitartelo.",
        error_no_player = "No habia ningun jugador disponible.",
        error_select_outfit_first = "Selecciona primero un atuendo.",
        error_no_container = "No habia un contenedor seleccionado o cercano disponible para Quick Fits.",
        error_save_empty = "Selecciona al menos un objeto llevado puesto para guardar este atuendo.",
        error_rename_missing = "Introduce un nombre antes de renombrar el atuendo.",
        default_outfit_name = "Atuendo %1",
        container_generic = "contenedor",
        container_nearby = "contenedor cercano",
    },
    FR = {
        bind_open = "Ouvrir Quick Fits",
        title = "Quick Fits",
        inventory_button = "Quick Fits",
        context_open = "Quick Fits...",
        editor_editing_named = "Modification : %1",
        editor_editing_new = "Modification : Nouvelle Tenue",
        fallback_outfit_name = "Tenue",
        debug_full_type = "fullType=%1",
        debug_body = "corps=%1",
        debug_item_type = "itemType=%1",
        debug_included_false = "included=false",
        debug_ignored_true = "ignored=true",
        button_save = "Enregistrer",
        button_capture_current = "Definir Sur Ce Qui Est Porte",
        button_new = "Nouveau",
        button_wear = "Porter",
        button_add = "Ajouter",
        button_take_off = "Retirer",
        button_place_container = "Mettre Dans Le Conteneur",
        button_delete = "Supprimer",
        button_stop = "Arreter",
        tooltip_wear =
        "Fait correspondre exactement votre equipement porte a cette tenue, en retirant d'abord tout ce qui n'en fait pas partie.",
        tooltip_add =
        "Ajoute cette tenue par-dessus ce que vous portez deja, en remplacant seulement les emplacements en conflit.",
        tooltip_take_off = "Retire uniquement les objets portes de cette tenue et les place dans votre inventaire.",
        tooltip_place_container =
        "Deplace les objets de la tenue dans un conteneur, en utilisant d'abord le conteneur selectionne puis le plus proche.",
        label_outfits = "Tenues",
        label_items_in_outfit = "Objets de la Tenue",
        label_item_singular = "objet",
        label_item_plural = "objets",
        label_worn = "PORTE",
        drop_hint_drag_here = "Glissez ici des objets portables",
        drop_hint_capture = "ou utilisez Capturer le Porte pour recuperer votre equipement actuel",
        drop_hint_release = "Relachez pour ajouter les objets portables glisses",
        debug_preview_language = "Langue de Previsualisation",
        progress_interrupted = "Interrompu",
        progress_completed_phase = "Termine : %1 (%2 / %3)",
        result_apply_failed = "Quick Fits n'a pas pu appliquer la tenue selectionnee.",
        result_action_apply = "appliquee.",
        result_action_remove = "retiree.",
        result_action_add = "ajoutee.",
        result_action_wear = "portee exactement.",
        result_action_place = "placee dans le conteneur.",
        result_outfit_action = "%1 %2",
        result_equipped = "%1 objet(s) equipes.",
        result_removed = "%1 objet(s) retires.",
        result_blocked = "Bloque par des objets portes : %1.",
        result_moved = "%1 objet(s) deplaces.",
        result_moved_target = "%1 objet(s) deplaces dans %2.",
        result_missing = "Manquants : %1.",
        draft_error_wearable_duplicates =
        "Seuls les objets portables peuvent etre ajoutes, et les doublons glisses ont ete ignores.",
        draft_overlay_wearable_duplicates =
        "Seuls les objets portables ont leur place ici. Les doublons ont ete ignores.",
        draft_error_only_wearable = "Seuls les objets portables peuvent etre ajoutes a un Quick Fit.",
        draft_overlay_only_wearable = "Seuls les objets portables peuvent etre deposes dans une tenue.",
        draft_error_already_present = "Ces objets sont deja dans ce Quick Fit.",
        draft_overlay_already_present = "Cet objet portable est deja dans cette tenue.",
        draft_added = "%1 objet(s) portable(s) ajoute(s) au brouillon.",
        draft_added_ignored = " %1 doublon(s) et %2 objet(s) non portables ignores.",
        status_selected_outfit = "Tenue selectionnee : %1",
        status_captured_current = "Les objets actuellement portes par le joueur ont ete recuperes dans l'editeur.",
        status_new_draft =
        "Nouveau brouillon de tenue vide cree. Glissez-y des objets portables ou utilisez Capturer le Porte.",
        status_saved_changes = "Modifications enregistrees pour la tenue : %1",
        status_saved_new = "Tenue enregistree : %1",
        status_select_before_delete = "Selectionnez une tenue avant de la supprimer.",
        delete_confirm = "Supprimer %1 ?",
        status_deleted = "La tenue selectionnee a ete supprimee.",
        status_delete_failed = "Quick Fits n'a pas pu supprimer la tenue selectionnee.",
        status_select_before_wear = "Selectionnez une tenue avant de la porter.",
        status_select_before_add = "Selectionnez une tenue avant de l'ajouter.",
        status_select_before_place = "Selectionnez une tenue avant de la placer dans un conteneur.",
        status_select_before_remove = "Selectionnez une tenue avant de la retirer.",
        error_no_player = "Aucun joueur n'etait disponible.",
        error_select_outfit_first = "Selectionnez d'abord une tenue.",
        error_no_container = "Aucun conteneur selectionne ou proche n'etait disponible pour Quick Fits.",
        error_save_empty = "Selectionnez au moins un objet porte pour enregistrer cette tenue.",
        error_rename_missing = "Saisissez un nom avant de renommer la tenue.",
        default_outfit_name = "Tenue %1",
        container_generic = "conteneur",
        container_nearby = "conteneur proche",
    },
    PTBR = {
        bind_open = "Abrir Quick Fits",
        title = "Quick Fits",
        inventory_button = "Quick Fits",
        context_open = "Quick Fits...",
        editor_editing_named = "Editando: %1",
        editor_editing_new = "Editando: Novo Traje",
        fallback_outfit_name = "Traje",
        debug_full_type = "fullType=%1",
        debug_body = "corpo=%1",
        debug_item_type = "itemType=%1",
        debug_included_false = "included=false",
        debug_ignored_true = "ignored=true",
        button_save = "Salvar",
        button_capture_current = "Definir Para O Que Esta Vestido",
        button_new = "Novo",
        button_wear = "Vestir",
        button_add = "Adicionar",
        button_take_off = "Tirar",
        button_place_container = "Colocar No Contenedor",
        button_delete = "Excluir",
        button_stop = "Parar",
        tooltip_wear =
        "Faz suas roupas equipadas corresponderem exatamente a este traje, desequipando antes tudo o que nao faz parte dele.",
        tooltip_add = "Coloca este traje sobre o que voce ja esta vestindo, substituindo apenas os espacos em conflito.",
        tooltip_take_off = "Remove apenas os itens vestidos deste traje e os coloca no seu inventario.",
        tooltip_place_container =
        "Move os itens do traje para um contenedor, usando primeiro o contenedor selecionado e depois o mais proximo.",
        label_outfits = "Trajes",
        label_items_in_outfit = "Itens do Traje",
        label_item_singular = "item",
        label_item_plural = "itens",
        label_worn = "VESTIDO",
        drop_hint_drag_here = "Arraste itens vestiveis para ca",
        drop_hint_capture = "ou use Capturar Vestidos para pegar seu equipamento atual",
        drop_hint_release = "Solte para adicionar os itens vestiveis arrastados",
        debug_preview_language = "Idioma de Previa",
        progress_interrupted = "Interrompido",
        progress_completed_phase = "Concluido: %1 (%2 / %3)",
        result_apply_failed = "Quick Fits nao conseguiu aplicar o traje selecionado.",
        result_action_apply = "aplicado.",
        result_action_remove = "tirado.",
        result_action_add = "adicionado.",
        result_action_wear = "vestido exatamente.",
        result_action_place = "colocado no contenedor.",
        result_outfit_action = "%1 %2",
        result_equipped = "%1 item(ns) equipados.",
        result_removed = "%1 item(ns) removidos.",
        result_blocked = "Bloqueado por itens vestidos: %1.",
        result_moved = "%1 item(ns) movidos.",
        result_moved_target = "%1 item(ns) movidos para %2.",
        result_missing = "Faltando: %1.",
        draft_error_wearable_duplicates =
        "Apenas itens vestiveis podem ser adicionados, e duplicatas arrastadas foram ignoradas.",
        draft_overlay_wearable_duplicates = "Apenas itens vestiveis pertencem aqui. Duplicatas foram ignoradas.",
        draft_error_only_wearable = "Apenas itens vestiveis podem ser adicionados a um Quick Fit.",
        draft_overlay_only_wearable = "Apenas itens vestiveis podem ser soltos em um traje.",
        draft_error_already_present = "Esses itens ja estao neste Quick Fit.",
        draft_overlay_already_present = "Esse item vestivel ja esta neste traje.",
        draft_added = "%1 item(ns) vestivel(is) adicionados ao rascunho.",
        draft_added_ignored = " %1 duplicata(s) e %2 item(ns) nao vestivel(is) ignorados.",
        status_selected_outfit = "Traje selecionado: %1",
        status_captured_current = "Os itens atualmente vestidos pelo jogador foram capturados no editor.",
        status_new_draft = "Novo rascunho de traje vazio iniciado. Arraste itens vestiveis ou use Capturar Vestidos.",
        status_saved_changes = "Alteracoes salvas no traje: %1",
        status_saved_new = "Traje salvo: %1",
        status_select_before_delete = "Selecione um traje antes de exclui-lo.",
        delete_confirm = "Excluir %1?",
        status_deleted = "O traje selecionado foi excluido.",
        status_delete_failed = "Quick Fits nao conseguiu excluir o traje selecionado.",
        status_select_before_wear = "Selecione um traje antes de vesti-lo.",
        status_select_before_add = "Selecione um traje antes de adiciona-lo.",
        status_select_before_place = "Selecione um traje antes de coloca-lo em um contenedor.",
        status_select_before_remove = "Selecione um traje antes de tira-lo.",
        error_no_player = "Nenhum jogador estava disponivel.",
        error_select_outfit_first = "Selecione um traje primeiro.",
        error_no_container = "Nenhum contenedor selecionado ou proximo estava disponivel para o Quick Fits.",
        error_save_empty = "Selecione pelo menos um item vestido para salvar este traje.",
        error_rename_missing = "Digite um nome antes de renomear o traje.",
        default_outfit_name = "Traje %1",
        container_generic = "contenedor",
        container_nearby = "contenedor proximo",
    },
    RU = {
        bind_open = "Otkryt Quick Fits",
        title = "Quick Fits",
        inventory_button = "Quick Fits",
        context_open = "Quick Fits...",
        editor_editing_named = "Redaktirovanie: %1",
        editor_editing_new = "Redaktirovanie: Novyi Komplekt",
        fallback_outfit_name = "Komplekt",
        debug_full_type = "fullType=%1",
        debug_body = "telo=%1",
        debug_item_type = "itemType=%1",
        debug_included_false = "included=false",
        debug_ignored_true = "ignored=true",
        button_save = "Sokhranit",
        button_capture_current = "Vzjat Tekushchee Nadetoe",
        button_new = "Novyi",
        button_wear = "Nadet",
        button_add = "Dobavit",
        button_take_off = "Snyat",
        button_place_container = "Polozhit V Konteiner",
        button_delete = "Udalit",
        button_stop = "Ostanovit",
        tooltip_wear = "Tochno privodit vashe nadetoe snaryazhenie k etomu komplektu, snimaya vse lishnee pered etim.",
        tooltip_add = "Nadevaet etot komplekt poverkh togo, chto uzhe nadeto, zamenyaya tolko konfliktuyushchie sloty.",
        tooltip_take_off = "Snimaet tolko veshchi iz etogo komplekta i kladet ikh v inventar.",
        tooltip_place_container =
        "Peremeshchaet predmety komplekta v konteiner, snachala v vybrannyi, zatem v blizhaishii.",
        label_outfits = "Komplekty",
        label_items_in_outfit = "Predmety Komplekta",
        label_item_singular = "predmet",
        label_item_plural = "predmetov",
        label_worn = "NADETO",
        drop_hint_drag_here = "Peretashchite syuda nosimye predmety",
        drop_hint_capture = "ili ispolzuyte Zahvat Nadetogo, chtoby vzyat tekushchee snaryazhenie",
        drop_hint_release = "Otpustite, chtoby dobavit peretashchennye nosimye predmety",
        debug_preview_language = "Yazyk Predprosmotra",
        progress_interrupted = "Prervano",
        progress_completed_phase = "Zaversheno: %1 (%2 / %3)",
        result_apply_failed = "Quick Fits ne smog primenit vybrannyi komplekt.",
        result_action_apply = "primenen.",
        result_action_remove = "snyat.",
        result_action_add = "dobavlen.",
        result_action_wear = "nade t tochno.",
        result_action_place = "perelozhen v konteiner.",
        result_outfit_action = "%1 %2",
        result_equipped = "Nadeto %1 predmet(ov).",
        result_removed = "Snyato %1 predmet(ov).",
        result_blocked = "Zablokirovano nadetymi predmetami: %1.",
        result_moved = "Peremeshcheno %1 predmet(ov).",
        result_moved_target = "Peremeshcheno %1 predmet(ov) v %2.",
        result_missing = "Otsutstvuyut: %1.",
        draft_error_wearable_duplicates =
        "Dobavlyat mozhno tolko nosimye predmety, peretashchennye dublikaty byli proignorirovany.",
        draft_overlay_wearable_duplicates = "Syuda otnosyatsya tolko nosimye predmety. Dublikaty proignorirovany.",
        draft_error_only_wearable = "V Quick Fit mozhno dobavlyat tolko nosimye predmety.",
        draft_overlay_only_wearable = "V komplekt mozhno brosat tolko nosimye predmety.",
        draft_error_already_present = "Eti predmety uzhe est v etom Quick Fit.",
        draft_overlay_already_present = "Etot nosimyi predmet uzhe est v etom komplekte.",
        draft_added = "V chernovik dobavleno %1 nosimykh predmet(ov).",
        draft_added_ignored = " Proignorirovano %1 dublikat(ov) i %2 ne-nosimykh predmet(ov).",
        status_selected_outfit = "Vybran komplekt: %1",
        status_captured_current = "Tekushchie nadetye predmety igroka skopirovany v redaktor.",
        status_new_draft =
        "Nachat novyi pustoi chernovik komplekta. Peretashchite nosimye predmety ili ispolzuite Zahvat Nadetogo.",
        status_saved_changes = "Izmeneniya komplekta sokhraneny: %1",
        status_saved_new = "Komplekt sokhranen: %1",
        status_select_before_delete = "Vyberite komplekt pered udaleniyem.",
        delete_confirm = "Udalit %1?",
        status_deleted = "Vybrannyi komplekt udalen.",
        status_delete_failed = "Quick Fits ne smog udalit vybrannyi komplekt.",
        status_select_before_wear = "Vyberite komplekt pered tem kak nadet ego.",
        status_select_before_add = "Vyberite komplekt pered dobavleniyem.",
        status_select_before_place = "Vyberite komplekt pered peremeshcheniem v konteiner.",
        status_select_before_remove = "Vyberite komplekt pered tem kak snyat ego.",
        error_no_player = "Igrok nedostupen.",
        error_select_outfit_first = "Snachala vyberite komplekt.",
        error_no_container = "Dlya Quick Fits net vybrannogo ili blizhaishego konteinera.",
        error_save_empty = "Vyberite khotya by odin nadetyi predmet, chtoby sokhranit etot komplekt.",
        error_rename_missing = "Vvedite imya pered pereimenovaniem komplekta.",
        default_outfit_name = "Komplekt %1",
        container_generic = "konteiner",
        container_nearby = "blizhaishii konteiner",
    },
    CN = {
        bind_open = "DaKai Quick Fits",
        title = "Quick Fits",
        inventory_button = "Quick Fits",
        context_open = "Quick Fits...",
        editor_editing_named = "BianJi: %1",
        editor_editing_new = "BianJi: Xin TaoZhuang",
        fallback_outfit_name = "TaoZhuang",
        debug_full_type = "fullType=%1",
        debug_body = "buwei=%1",
        debug_item_type = "itemType=%1",
        debug_included_false = "included=false",
        debug_ignored_true = "ignored=true",
        button_save = "BaoCun",
        button_capture_current = "SheWei DangQian ChuanDai",
        button_new = "XinJian",
        button_wear = "ChuanShang",
        button_add = "TianJia",
        button_take_off = "TuoXia",
        button_place_container = "FangRu RongQi",
        button_delete = "ShanChu",
        button_stop = "TingZhi",
        tooltip_wear =
        "Rang ni dangqian chuanzhe de zhuangbei yu ci taozhuang wanquan yizhi, bing xian xiaxia bu zai qi zhong de wu pin.",
        tooltip_add = "Ba ci taozhuang diejia dao ni yijing chuanzhe de zhuangbei shang, zhihui tihuan chongtu de buwei.",
        tooltip_take_off = "Zhishan chu ci taozhuang de chuanzai wu pin bing fang ru ni de beibao.",
        tooltip_place_container =
        "Ba taozhuang wu pin yidong dao rongqi zhong, youxian shiyong xuanzhong rongqi, ranhou shiyong zuijin de rongqi.",
        label_outfits = "TaoZhuang",
        label_items_in_outfit = "TaoZhuang WuPin",
        label_item_singular = "wu pin",
        label_item_plural = "wu pin",
        label_worn = "YI CHUAN",
        drop_hint_drag_here = "Jiang ke chuandai wu pin tuo dao zheli",
        drop_hint_capture = "huo shi yong BuHuo ChuanDai lai duqu ni dangqian de zhuangbei",
        drop_hint_release = "Song kai yi tianjia tuo dong de ke chuandai wu pin",
        debug_preview_language = "YuLan YuYan",
        progress_interrupted = "Yi ZhongDuan",
        progress_completed_phase = "Yi WanCheng: %1 (%2 / %3)",
        result_apply_failed = "Quick Fits wu fa ying yong suo xuan tao zhuang.",
        result_action_apply = "yi yingyong.",
        result_action_remove = "yi tuoxia.",
        result_action_add = "yi tianjia.",
        result_action_wear = "yi jingque chuandai.",
        result_action_place = "yi fangru rongqi.",
        result_outfit_action = "%1 %2",
        result_equipped = "Yi chuandai %1 ge wu pin.",
        result_removed = "Yi yichu %1 ge wu pin.",
        result_blocked = "Bei yi chuan wu pin zu dang: %1.",
        result_moved = "Yi yidong %1 ge wu pin.",
        result_moved_target = "Yi jiang %1 ge wu pin yidong dao %2.",
        result_missing = "Que shao: %1.",
        draft_error_wearable_duplicates = "Zhi neng tianjia ke chuandai wu pin, tuo dong de chongfu xiang yi bei hulu.",
        draft_overlay_wearable_duplicates = "Zheli zhi ying fang ke chuandai wu pin. Chongfu xiang yi bei hulu.",
        draft_error_only_wearable = "Quick Fit zhi neng tianjia ke chuandai wu pin.",
        draft_overlay_only_wearable = "Zhi neng jiang ke chuandai wu pin fang ru tao zhuang.",
        draft_error_already_present = "Zhexie wu pin yi jing zai ci Quick Fit zhong.",
        draft_overlay_already_present = "Gai ke chuandai wu pin yi jing zai ci tao zhuang zhong.",
        draft_added = "Yi xiang cao gao zhong tianjia %1 ge ke chuandai wu pin.",
        draft_added_ignored = " Hu lue le %1 ge chongfu xiang he %2 ge bu ke chuandai wu pin.",
        status_selected_outfit = "Yi xuan tao zhuang: %1",
        status_captured_current = "Yi jiang wanjia dangqian chuanzai wu pin buhuo dao bianjiqi.",
        status_new_draft =
        "Yi chuangjian xin de kong tao zhuang cao gao. Tuo ru ke chuandai wu pin huo shi yong BuHuo ChuanDai.",
        status_saved_changes = "Yi bao cun tao zhuang genggai: %1",
        status_saved_new = "Yi bao cun tao zhuang: %1",
        status_select_before_delete = "Shanchu qian qing xian xuanze yi ge tao zhuang.",
        delete_confirm = "Shanchu %1?",
        status_deleted = "Yi shanchu suo xuan tao zhuang.",
        status_delete_failed = "Quick Fits wu fa shanchu suo xuan tao zhuang.",
        status_select_before_wear = "Chuandai qian qing xian xuanze yi ge tao zhuang.",
        status_select_before_add = "Tianjia qian qing xian xuanze yi ge tao zhuang.",
        status_select_before_place = "Fang ru rongqi qian qing xian xuanze yi ge tao zhuang.",
        status_select_before_remove = "Tuo xia qian qing xian xuanze yi ge tao zhuang.",
        error_no_player = "Mei you ke yong wanjia.",
        error_select_outfit_first = "Qing xian xuanze yi ge tao zhuang.",
        error_no_container = "Mei you ke yong de yi xuan huo fujin rongqi gong Quick Fits shiyong.",
        error_save_empty = "Qing xuanze zhi shao yi ge yi chuan wu pin lai bao cun ci tao zhuang.",
        error_rename_missing = "Chongmingming tao zhuang qian qing xian shuru mingcheng.",
        default_outfit_name = "TaoZhuang %1",
        container_generic = "rongqi",
        container_nearby = "fujin rongqi",
    },
}

Localization.previewLanguage = Localization.previewLanguage or Localization.PREVIEW_LANGUAGE_AUTO

local function formatText(text, ...)
    local formatted = tostring(text or "")
    for index = 1, select("#", ...) do
        local value = tostring(select(index, ...) or "")
        formatted = formatted:gsub("%%" .. tostring(index), value)
    end
    return formatted
end

local function getLanguageStrings(languageCode)
    return STRINGS[languageCode] or STRINGS.EN
end

local function getPreviewText(languageCode, key, ...)
    local languageStrings = getLanguageStrings(languageCode)
    local text = languageStrings[key] or STRINGS.EN[key] or key
    return formatText(text, ...)
end

function Localization.getLanguageLabel(languageCode)
    return PREVIEW_LANGUAGE_LABELS[languageCode] or tostring(languageCode or Localization.PREVIEW_LANGUAGE_AUTO)
end

function Localization.getAvailablePreviewLanguages()
    return {
        Localization.PREVIEW_LANGUAGE_AUTO,
        "EN",
        "DE",
        "ES",
        "FR",
        "PTBR",
        "RU",
        "CN",
    }
end

function Localization.setPreviewLanguage(languageCode)
    if not languageCode or languageCode == "" or not PREVIEW_LANGUAGE_LABELS[languageCode] then
        Localization.previewLanguage = Localization.PREVIEW_LANGUAGE_AUTO
        return
    end

    Localization.previewLanguage = languageCode
end

function Localization.getPreviewLanguage()
    return Localization.previewLanguage or Localization.PREVIEW_LANGUAGE_AUTO
end

function Localization.getPreviewText(key, ...)
    return getPreviewText(Localization.getPreviewLanguage(), key, ...)
end

function Localization.getText(key, ...)
    local previewLanguage = Localization.getPreviewLanguage()
    if previewLanguage ~= Localization.PREVIEW_LANGUAGE_AUTO then
        return getPreviewText(previewLanguage, key, ...)
    end

    local fullKey = Localization.KEY_PREFIX .. tostring(key or "")
    local args = { ... }
    local gameGetText = (_G and rawget(_G, "getText")) or getText
    if type(gameGetText) == "function" then
        local ok, translated = pcall(function()
            if unpackArgs and #args > 0 then
                return gameGetText(fullKey, unpackArgs(args, 1, #args))
            end

            return gameGetText(fullKey)
        end)
        if ok and translated and translated ~= "" and translated ~= fullKey then
            return translated
        end
    end

    return getPreviewText("EN", key, ...)
end
